name: Check for valid whitespace usage in PortAudio source files

on: [push, pull_request]

jobs:
  run-pa-whitelint-dot-py:

    runs-on: ubuntu-latest
    name: Ubuntu

    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-python@v6
      with:
        python-version: '3.x'
    - name: Run the pa_whitelint.py script
      run: python ./pa_whitelint.py
